### ISSUE TITLE
Sound on Android Stopping After 30 Times

### ISSUE THREAD

**Issue by ryanbrainard** [ryanbrainard/gwi#35]

**Comment by ryanbrainard** [comment]
Reproduced on emulator:

```
12-27 20:34:08.220  1736  9446 E OMXNodeInstance: getConfig(0xeba44240:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
12-27 20:34:08.223  1579  1579 W AshmemAllocator: ashmem_create_region(8192) returning hidl_memory(0xe981c180, 8192)
12-27 20:34:08.226  1579  1579 I chatty  : uid=1000(system) allocator@1.0-s identical 2 lines
12-27 20:34:08.238  1579  1579 W AshmemAllocator: ashmem_create_region(8192) returning hidl_memory(0xe981c180, 8192)
12-27 20:34:08.246  1579  1579 W AshmemAllocator: ashmem_create_region(9216) returning hidl_memory(0xe981c180, 9216)
12-27 20:34:08.252  1579  1579 I chatty  : uid=1000(system) allocator@1.0-s identical 2 lines
12-27 20:34:08.252  1579  1579 W AshmemAllocator: ashmem_create_region(9216) returning hidl_memory(0xe981c180, 9216)
12-27 20:34:08.285  9786 26592 W AudioFlinger: createTrack_l(): mismatch between requested flags (00000008) and output flags (00000006)
12-27 20:34:08.288  9786 26592 D AudioFlinger: Client defaulted notificationFrames to 3675 for frameCount 11025
12-27 20:34:08.288  9786 26592 E AudioFlinger: no more tracks available
12-27 20:34:08.288  9786 26592 E AudioFlinger: createTrack_l() initCheck failed -12; no control block?
12-27 20:34:08.289 12640 13646 E IAudioFlinger: createTrack returned error -12
12-27 20:34:08.289 12640 13646 E AudioTrack: AudioFlinger could not create track, status: -12 output -1059523632
12-27 20:34:08.289 12640 13646 E AudioTrack-JNI: Error -12 initializing AudioTrack
12-27 20:34:08.289 12640 13646 D AudioTrack: no metrics gathered, track status=-12
12-27 20:34:08.289 12640 13646 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: Renderer error.
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: com.google.android.exoplayer2.e
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.a.j.a(MediaCodecAudioRenderer.java:439)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.f.b.b(MediaCodecRenderer.java:998)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.f.b.a(MediaCodecRenderer.java:552)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.i.g(ExoPlayerImplInternal.java:560)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.i.handleMessage(ExoPlayerImplInternal.java:306)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:193)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.a.f$b: AudioTrack init failed: 0, Config(44100, 12, 44100)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.a.h.x(DefaultAudioSink.java:1180)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.a.h.l(DefaultAudioSink.java:487)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.a.h.a(DefaultAudioSink.java:544)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.a.j.a(MediaCodecAudioRenderer.java:433)
12-27 20:34:08.291 12640 13646 E ExoPlayerImplInternal: 	... 7 more
12-27 20:34:08.312 12640 12715 I ExoPlayerImpl: Release 812c34e [ExoPlayerLib/2.6.1] [generic_x86, Android SDK built for x86, Google, 28] [goog.exo.core]
```

**Comment by ryanbrainard** [comment]
Silent error on first sound:

```
12-27 22:51:45.875   663  3176 I ReactNativeJS: fn=play at=sync-start
12-27 22:51:45.911   663  3177 I ExoPlayerImpl: Init b15591 [ExoPlayerLib/2.6.1] [generic_x86, Android SDK built for x86, Google, 28]
12-27 22:51:45.911   663  3177 D i       : WARNING: getPackageName called on ScopedContext
12-27 22:51:45.921   663  3177 W AudioManager: Use of stream types is deprecated for operations other than volume control
12-27 22:51:45.921   663  3177 W AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
12-27 22:51:45.922  1931  1980 I MediaFocusControl: requestAudioFocus() from uid/pid 10085/663 clientId=android.media.AudioManager@6b885e8abi27_0_0.host.exp.exponent.modules.api.av.AVModule@2b9ccf6 callingPack=host.exp.exponent req=3 flags=0x0 sdk=26
12-27 22:51:45.939   663  3216 I OMXClient: IOmx service obtained
12-27 22:51:45.940  1736  9446 I OMXMaster: makeComponentInstance(OMX.google.mp3.decoder) in omx@1.0-service process
12-27 22:51:45.953  1736  9446 E OMXNodeInstance: getConfig(0xeba44300:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
12-27 22:51:45.957  1579  1579 W AshmemAllocator: ashmem_create_region(8192) returning hidl_memory(0xe981c180, 8192)
12-27 22:51:45.958  1579  1579 I chatty  : uid=1000(system) allocator@1.0-s identical 2 lines
12-27 22:51:45.959  1579  1579 W AshmemAllocator: ashmem_create_region(8192) returning hidl_memory(0xe981c180, 8192)
12-27 22:51:45.960  1579  1579 W AshmemAllocator: ashmem_create_region(9216) returning hidl_memory(0xe981c180, 9216)
12-27 22:51:45.961  1579  1579 I chatty  : uid=1000(system) allocator@1.0-s identical 2 lines
12-27 22:51:45.962  1579  1579 W AshmemAllocator: ashmem_create_region(9216) returning hidl_memory(0xe981c180, 9216)
12-27 22:51:45.979   663  3176 I ReactNativeJS: 'fn=play at=then playback=', true
12-27 22:51:45.986  9786  9796 W AudioFlinger: createTrack_l(): mismatch between requested flags (00000008) and output flags (00000006)
12-27 22:51:45.988  9786  9796 D AudioFlinger: Client defaulted notificationFrames to 3675 for frameCount 11025
12-27 22:51:46.010  9787 21947 W audio_hw_generic: Not supplying enough data to HAL, expected position 5782356 , only wrote 5782320
12-27 22:51:46.162  9787 21947 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
12-27 22:51:46.207  9787 21947 I chatty  : uid=1041(audioserver) writer identical 3 lines
12-27 22:51:46.222  9787 21947 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
```
